"""Keep the plain-English library honest: ``docs/For NonCoders/`` and its bookkeeping.

The library is a translation of the repository for a reader who does not
write code: one page per program file and per handoff note, each naming the
original it explains. A page is wrong silently in three ways - a new handoff
note arrives with no page, an original changes after its page was written,
or a page is moved or re-tagged and the start page no longer lists it right.
Nothing else in the repository notices any of them, and a translation nobody
re-checks is worse than none, because the owner trusts it.

This tool owns the bookkeeping, the way ``tools/vocab_report.py`` owns its
report. It fingerprints every original (SHA-256, of the bytes Git commits -
``git_text_auto_eol_lf``, the map's rule, decision 151 - so a CRLF working
copy is not stale on a CI checkout) into ``docs/For NonCoders/pages.json``,
generates the start page (``README.md``) from the pages' own Tags lines, and
``check`` fails, naming each page and the exact fix, on any gap. Three
triggers run ``check``, cheapest first: a Claude Code Stop hook (``hook``),
so an AI session that leaves a page stale is told to fix it before it ends;
``tests/test_noncoder_pages.py``, a guard every gate runs; and CI.

Only the bookkeeping is automated. Writing a page stays with the agent: an AI
may read handoff notes and program files (they are not client documents, so
the first standing rule is untouched), and a person can read the diff. The
tool never writes prose and the hook never edits a page - a skeleton would
pass a structural check and say nothing; a hash on each page would churn
with every page edit; a hook that wrote pages would put words in the firm's
mouth that nobody read.

``pages.json`` and ``README.md`` are generated. Never hand-edit either;
``stamp`` is the one way they change, run after a page is written, updated,
or reviewed and found still accurate (``organize`` only carries a moved page's
record to its new path). ``stamp`` also keeps the version a page replaces, in
``7 - History/Earlier Versions``, from Git's ``HEAD``.

The mechanical part fixes itself: ``organize`` moves and renames pages to where
the rules say - a handoff page by its note's name, a program page by its first
topic - retires a page whose original was removed - gone from the working tree and
from Git's ``HEAD``, so a rename is never mistaken for a removal - to
``7 - History/Retired Pages``, and renumbers a stage folder when a note is
inserted. It never edits prose (the one text edit is the Retired line), never
overwrites, and never touches an original: other files and tests cite those
paths. The Stop hook runs it (so the hook does move pages and adds the Retired
line, and never edits a page's prose), then ``check``, so only the writing is
handed back to the agent. A hook that moved pages exits 2 once so the session
stages the moves and refreshes the code map. History is
exempt from the page rules: what a page said then is a record, not a claim.

::

    python tools/noncoder_pages.py check            # is the library current? exit 1 if not
    python tools/noncoder_pages.py todo             # the same findings as a work order (exit 0)
    python tools/noncoder_pages.py organize [--dry-run]   # move and rename pages to where the rules say
    python tools/noncoder_pages.py stamp [PAGE ...] # record fingerprints, regenerate the start page
    python tools/noncoder_pages.py place NOTE       # where a new note's page belongs
    python tools/noncoder_pages.py hook             # the Stop hook (reads its JSON on stdin)
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))   # run as a script: the sibling tool must import

from tools.repo_map import git_text_auto_eol_lf  # noqa: E402

LIBRARY = "docs/For NonCoders"
RECORD = f"{LIBRARY}/pages.json"
START_PAGE = f"{LIBRARY}/README.md"
STYLE_FILE = "docs/noncoder-style.md"
SCHEMA_VERSION = 2
MAX_LINES = 200
HOOK_LIMIT = 20
GENERATED_FOOTER = "Generated by tools/noncoder_pages.py stamp; do not edit by hand."
#: Decision 209: no page may tell a person to run something once after installing.
ONE_TIME_STEP = re.compile(r"once after (install|upgrad)", re.IGNORECASE)

#: Folders of the library, in the order the start page lists them.
START, WORKS, BUILD, TESTS, RULES, WORK_HISTORY, ARCHIVE = (
    "1 - Start Here", "2 - How the Program Works", "3 - Building and Installing",
    "4 - Testing and Checks", "5 - Rules, Plans and Decisions", "6 - Work History (Handoff Notes)",
    "7 - History")
RETIRED, EARLIER = "Retired Pages", "Earlier Versions"
FOLDERS = (
    (START, "Where the pilot stands today."),
    (WORKS, "The safety walls around the app window, the engine, and the Windows schedule."),
    (BUILD, "How the program is built, packed into an installer, and kept safe from bad outside parts."),
    (TESTS, "The automatic checks: on this computer, on the office PC, and on GitHub."),
    (RULES, "The rules for AI helpers, the decision log, the build plan and the code map."),
    (WORK_HISTORY, "What each work session did, stage by stage, in the order it happened."),
    (ARCHIVE, "Pages whose file was removed, and earlier versions of pages that were rewritten."),
)
#: Where a program page belongs, by its first Topic: (section folder, default subfolder or "").
PROGRAM_HOMES = {
    "Safety": (WORKS, "Safety Walls"), "App window": (WORKS, "Safety Walls"),
    "Engine": (WORKS, "Engine and Schedule"), "Schedule": (WORKS, "Engine and Schedule"),
    "Installer": (BUILD, "Installer"), "Building": (BUILD, "Building the App"),
    "Supply-chain safety": (BUILD, "Supply-Chain Safety"),
    "Testing": (TESTS, "Tests on This Computer"), "GitHub costs": (TESTS, "Tests on This Computer"),
    "Rules and decisions": (RULES, ""), "Code map": (RULES, ""), "Wording": (RULES, ""), "Screen": (RULES, ""),
}

#: The tag vocabularies, in one place; the start page's tag tables are generated from these.
KINDS = {
    "Overview": "Where the whole project stands.",
    "Program file": "Explains a file the program is made of.",
    "Build": "A work session that built something new.",
    "Review": "An independent check of a build, by a session that did not build it.",
    "Fix round": "A work session that fixed what a review found, and nothing more.",
    "Final check": "A last check of the whole screen before it is called done.",
    "Rulings": "Jason's decisions and the plan updated to match them.",
}
TOPICS = {
    "Safety": "The walls that keep client files safe from the app window.",
    "App window": "The part of the program you click on.",
    "Engine": "The part that sorts, renames and records documents.",
    "Schedule": "The Windows alarm clock that runs the sorting by itself.",
    "Installer": "The file that installs or upgrades the program on a computer.",
    "Building": "Turning the code into a program you can install.",
    "Supply-chain safety": "Checking every outside part the program uses has not been swapped.",
    "Testing": "The automatic checks.",
    "GitHub costs": "The rules that keep the GitHub bill down.",
    "Rules and decisions": "The written rules, plans and Jason's decisions.",
    "Code map": "The map of every file in the program.",
    "Screen": "The app's new screen, built in stages S1 to S8.",
    "Wording": "The exact words the app shows.",
}
STAGE_SHAPE = re.compile(r"S\d+[a-z]?")

#: The section headings of the two layouts, exactly as docs/noncoder-style.md gives them.
HANDOFF_HEADINGS = (
    "In one sentence", "What this session was asked to do", "What it did",
    "What it found wrong, or what was left to do",
    "Decisions (made by Jason, or waiting for Jason)", "Words to know")
PROGRAM_HEADINGS = (
    "In one sentence", "What it is", "What it does, step by step", "Why it matters to the firm",
    "What must never be changed without a programmer", "Words to know")
PROGRAM_KIND = "Program file"

TAGS_LINE = re.compile(
    r"^\*\*Tags:\*\* Kind: (?P<kind>[^·]+?) · Topic: (?P<topics>[^·]+?)(?: · Stage: (?P<stage>\S+))?\s*$")


class LibraryError(Exception):
    """The library could not be read, or a note has nowhere to go."""


@dataclass(frozen=True, slots=True, order=True)
class Finding:
    """One thing wrong with the library, and the one action that fixes it."""

    kind: str          # missing, stale, orphan, malformed, start
    page: str          # repo-relative page to write or update; "" when the fix is `stamp` alone
    originals: tuple[str, ...]
    problem: str
    fix: str


@dataclass(frozen=True, slots=True)
class Page:
    path: str                      # repo-relative, posix
    title: str
    originals: tuple[str, ...]
    kind: str
    topics: tuple[str, ...]
    stage: str | None
    problems: tuple[str, ...]


# ------------------------------------------------------------------ reading ----


def fingerprint(path: Path) -> str:
    """SHA-256 of ``path`` as Git commits it (``git_text_auto_eol_lf``, decision 151)."""
    return hashlib.sha256(git_text_auto_eol_lf(path.read_bytes())).hexdigest()


def page_paths(root: Path) -> list[str]:
    """Every page: each ``*.md`` under the library except its start page and its history."""
    library = root / LIBRARY
    found = (p.relative_to(root).as_posix() for p in library.rglob("*.md"))
    return sorted(p for p in found if p != START_PAGE and not p.startswith(f"{LIBRARY}/{ARCHIVE}/"))


def history_paths(root: Path) -> list[str]:
    """Every page in ``7 - History``: retired pages and earlier versions."""
    return sorted(p.relative_to(root).as_posix() for p in (root / LIBRARY / ARCHIVE).rglob("*.md"))


def note_paths(root: Path) -> list[str]:
    """Every handoff note a page must translate."""
    notes = sorted(p.relative_to(root).as_posix() for p in (root / "pilot" / "handoffs").glob("*.md"))
    return sorted(notes + (["pilot/HANDOFF.md"] if (root / "pilot" / "HANDOFF.md").is_file() else []))


def parse_page(root: Path, path: str) -> Page:
    """A page's title, originals and tags, with every rule of the layout it breaks."""
    text = (root / path).read_text(encoding="utf-8")
    lines = text.splitlines()
    problems: list[str] = []
    title = lines[0][2:].strip() if lines and lines[0].startswith("# ") else ""
    if not title:
        problems.append("the first line is not a '# ' title")
    originals: tuple[str, ...] = ()
    named = next((ln for ln in lines if ln.startswith("**Original file:**")), None)
    if named is None:
        problems.append("no '**Original file:**' line")
    else:
        originals = tuple(re.findall(r"`([^`]+)`", named))
        if not originals:
            problems.append("the Original file line names no file in backticks")
        for original in originals:
            if not (root / original).is_file():
                problems.append(f"original `{original}` is not a file in the repository")
    kind, topics, stage = "", (), None
    tags = next((TAGS_LINE.match(ln) for ln in lines if ln.startswith("**Tags:**")), None)
    if tags is None:
        problems.append("no well-formed '**Tags:** Kind: ... · Topic: ...' line")
    else:
        kind = tags["kind"].strip()
        topics = tuple(t.strip() for t in tags["topics"].split(","))
        stage = tags["stage"]
        if kind not in KINDS:
            problems.append(f"unknown Kind {kind!r} (one of: {', '.join(KINDS)})")
        problems += [f"unknown Topic {t!r} (one of: {', '.join(TOPICS)})" for t in topics if t not in TOPICS]
        if stage is not None and not STAGE_SHAPE.fullmatch(stage):
            problems.append(f"Stage {stage!r} is not S, digits and an optional lowercase letter")
    headings = PROGRAM_HEADINGS if kind == PROGRAM_KIND else HANDOFF_HEADINGS
    present = {ln[3:].strip() for ln in lines if ln.startswith("## ")}
    problems += [f"missing the section '## {h}'" for h in headings if h not in present]
    if len(lines) > MAX_LINES:
        problems.append(f"{len(lines)} lines; the limit is {MAX_LINES}")
    if ONE_TIME_STEP.search(text):
        problems.append("tells a person to do something 'once after installing/upgrading' (decision 209)")
    return Page(path, title, originals, kind, topics, stage, tuple(problems))


def load_record(root: Path) -> dict[str, dict]:
    """``pages.json``'s pages, each ``{"page": <sha256 of the page>, "originals": {path: sha256}}``;
    empty when there is no record yet."""
    path = root / RECORD
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if data["version"] != SCHEMA_VERSION:
            raise LibraryError(f"{RECORD} is version {data['version']!r}, this tool writes {SCHEMA_VERSION}; "
                               "run: python tools/noncoder_pages.py stamp")
        return {page: {"page": str(entry["page"]), "originals": dict(entry["originals"])}
                for page, entry in data["pages"].items()}
    except (json.JSONDecodeError, KeyError, TypeError, ValueError, AttributeError) as exc:
        raise LibraryError(f"could not read {RECORD} ({type(exc).__name__}); run: "
                           "python tools/noncoder_pages.py stamp") from None


def render_record(pages: dict[str, dict]) -> bytes:
    body = {"version": SCHEMA_VERSION, "pages": pages}
    return (json.dumps(body, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


# --------------------------------------------------------------- start page ----


def _link(path: str, title: str) -> str:
    return f"[{title}](<{path}>)"


def _title_of(root: Path, path: str) -> str:
    """The first line's title of a history page, or its file name when it has none."""
    lines = (root / path).read_text(encoding="utf-8").splitlines()
    return lines[0][2:].strip() if lines and lines[0].startswith("# ") and lines[0][2:].strip() else Path(path).stem


def history_entries(root: Path) -> dict[str, list[tuple[str, str]]]:
    """The history pages by group (their folder under ``7 - History``) as (library path, title)."""
    groups: dict[str, list[tuple[str, str]]] = {RETIRED: [], EARLIER: []}
    prefix = f"{LIBRARY}/{ARCHIVE}/"
    for path in history_paths(root):
        group = path[len(prefix):].split("/")[0] if "/" in path[len(prefix):] else "Other"
        groups.setdefault(group, []).append((path[len(LIBRARY) + 1:], _title_of(root, path)))
    return {group: sorted(found) for group, found in groups.items()}


def render_start(pages: list[Page], history: dict[str, list[tuple[str, str]]] | None = None) -> str:
    """The start page, from the pages' own Tags lines; a page with broken tags is left out
    (``check`` reports it as malformed). History is listed last, under its own heading."""
    history = history or {RETIRED: [], EARLIER: []}
    prefix = LIBRARY + "/"
    entries = [(p.path[len(prefix):], p.title, p.kind, p.topics, p.stage)
               for p in pages if p.kind in KINDS and all(t in TOPICS for t in p.topics) and p.title]
    by_topic: dict[str, list] = {}
    by_kind: dict[str, list] = {}
    for entry in entries:
        by_kind.setdefault(entry[2], []).append(entry)
        for topic in entry[3]:
            by_topic.setdefault(topic, []).append(entry)
    lines = [
        "# For NonCoders: start here", "",
        "Every page in this folder explains one part of the Tax Document Tracker",
        "in plain words, for a reader who does not write code. Each page names the",
        "original file it explains, so a programmer can find it too.", "",
        "These pages explain; the originals decide. If a page here and its original",
        "ever disagree, the original is right, and this page needs fixing.", "",
        "Start with the [maintenance guide](../maintenance-guide.md), the plain-English",
        f"overview of the whole system, then [where the pilot stands](<{START}/Where the Pilot Stands (main handoff).md>).",
        "", "## How the folders are arranged", "",
        "| Folder | What is in it |", "|---|---|",
        *(f"| `{name}` | {meaning} |" for name, meaning in FOLDERS),
        "", "## What the tags mean", "",
        "Every page has a **Tags** line near the top, with up to three kinds of tag.", "",
        "**Kind** - what sort of page it is:", "",
        "| Kind | Meaning |", "|---|---|",
        *(f"| {kind} | {meaning} |" for kind, meaning in KINDS.items()),
        "", "**Topic** - what part of the system the page is about:", "",
        "| Topic | Meaning |", "|---|---|",
        *(f"| {topic} | {meaning} |" for topic, meaning in TOPICS.items()),
        "", "**Stage** - for work history pages, which build stage of the new screen",
        "(S1 to S8b) the session belonged to. Inside each stage folder the pages are",
        "numbered in the order they happened: build, review 1, fix round 1, review 2,",
        "and so on.", "", "## Every page, by topic", "",
    ]
    for topic in sorted(by_topic):
        lines += [f"### {topic}", ""]
        for path, title, kind, _, stage in sorted(by_topic[topic]):
            lines.append(f"- {_link(path, title)} - {kind}{f' ({stage})' if stage else ''}")
        lines.append("")
    lines += ["## Every page, by kind", ""]
    for kind in KINDS:
        found = sorted(by_kind.get(kind, []))
        lines += [f"### {kind} ({len(found)})", ""]
        lines += [f"- {_link(path, title)}" for path, title, *_ in found]
        lines.append("")
    lines += ["## History", "",
              "Pages whose file was removed, and earlier versions of pages that were rewritten.",
              "They record what a page said then; they are not kept up to date.", ""]
    for group, found in history.items():
        lines += [f"### {group} ({len(found)})", ""]
        lines += [f"- {_link(path, title)}" for path, title in found] or ["- none"]
        lines.append("")
    lines += ["---", "", GENERATED_FOOTER]
    return "\n".join(lines) + "\n"


# -------------------------------------------------------------------- check ----


def findings(root: Path) -> list[Finding]:
    """Everything wrong with the library, sorted; never writes."""
    paths = page_paths(root)
    pages = [parse_page(root, p) for p in paths]
    record = load_record(root)
    out: list[Finding] = []
    named = {o for page in pages for o in page.originals}
    for note in note_paths(root):
        if note not in named:
            try:
                where = place(root, note)
            except LibraryError as exc:
                out.append(Finding("missing", "", (note,), f"{note} has no plain-English page, and {exc}.",
                                   "a person creates or names the stage folder; then write the page, "
                                   "run organize and stamp it"))
                continue
            out.append(Finding("missing", where, (note,), f"{note} has no plain-English page.",
                               f"write the page at {where}, then stamp it"))
    for page in pages:
        for problem in page.problems:
            out.append(Finding("malformed", page.path, page.originals, f"{page.path}: {problem}.",
                               f"fix the page against {STYLE_FILE}"))
        held = record.get(page.path, {}).get("originals", {})
        for original in page.originals:
            if not (root / original).is_file() and _in_head(root, original):
                out.append(Finding("missing", page.path, (original,),
                                   f"original {original} is missing but not removed in Git: if it was renamed, "
                                   f"fix the page's Original file line; if it was deleted, commit the deletion.",
                                   f"fix {page.path}'s Original file line, or commit the deletion"))
            if (root / original).is_file() and held.get(original) != fingerprint(root / original):
                how = "has no recorded fingerprint" if original not in held else "changed after its page was stamped"
                out.append(Finding("stale", page.path, (original,), f"{page.path}: original {original} {how}.",
                                   f"update the page (or confirm it is still accurate), then "
                                   f"python tools/noncoder_pages.py stamp '{page.path}'"))
    by_path = {p.path: p for p in pages}
    for path, held in sorted(record.items()):
        if path not in by_path:
            out.append(Finding("orphan", "", (), f"pages.json records {path}, which is no longer a page.",
                               "python tools/noncoder_pages.py stamp"))
        else:
            for original in sorted(set(held["originals"]) - set(by_path[path].originals)):
                out.append(Finding("orphan", "", (original,),
                                   f"pages.json records {original} for {path}, which the page no longer names.",
                                   "python tools/noncoder_pages.py stamp"))
    for leftover in sorted((root / LIBRARY).rglob("*.organize-*")):
        rel = leftover.relative_to(root).as_posix()
        out.append(Finding("organize", rel, (), f"{rel} is left over from an organize that failed part way.",
                           "rename it back by hand: drop the '.organize-N' ending"))
    for path in history_paths(root):
        first = (root / path).read_text(encoding="utf-8").split("\n", 1)[0]
        if not first.startswith("# "):
            out.append(Finding("malformed", path, (), f"{path}: the first line is not a '# ' title.",
                               "start the history page with its '# ' title"))
    start = root / START_PAGE
    if not start.is_file() or start.read_bytes().replace(b"\r\n", b"\n") != \
            render_start(pages, history_entries(root)).encode("utf-8"):
        out.append(Finding("start", "", (), f"{START_PAGE} does not match what the pages' tags generate.",
                           "python tools/noncoder_pages.py stamp"))
    return sorted(out)


def work_order(found: list[Finding], limit: int | None = None) -> str:
    """The findings as a work order an agent can follow: the page, the originals, the style file."""
    shown = found if limit is None else found[:limit]
    lines: list[str] = []
    for n, f in enumerate(shown, 1):
        lines.append(f"{n}. [{f.kind}] {f.problem}")
        if f.page:
            lines.append(f"   page: {f.page}")
        if f.originals:
            lines.append(f"   read: {', '.join(f.originals)}")
        lines.append(f"   do: {f.fix}")
    if limit is not None and len(found) > limit:
        lines.append(f"... and {len(found) - limit} more (run: python tools/noncoder_pages.py todo)")
    lines.append(f"Style rules for every page: {STYLE_FILE}. Write in plain words; never invent a fact.")
    return "\n".join(lines)


# -------------------------------------------------------------------- stamp ----


def _keep_earlier(root: Path, page: str, recorded: str, today: datetime.date) -> str:
    """Write the version a page replaces to ``7 - History/Earlier Versions``, taken from Git's ``HEAD``
    when ``HEAD`` still holds exactly the text that was stamped. Returns the one line to say."""
    try:
        shown = subprocess.run(["git", "show", f"HEAD:{page}"], cwd=root, capture_output=True,
                               check=True, timeout=30).stdout
    except (OSError, subprocess.SubprocessError):
        return f"no earlier version of {page} kept: Git has no HEAD version of it"
    if hashlib.sha256(git_text_auto_eol_lf(shown)).hexdigest() != recorded:
        return f"no earlier version of {page} kept: HEAD holds a version that was never stamped"
    folder = root / LIBRARY / ARCHIVE / EARLIER
    folder.mkdir(parents=True, exist_ok=True)
    stem = f"{Path(page).stem} - until {today.isoformat()}"
    target, n = folder / f"{stem}.md", 1
    while target.exists():
        n += 1
        target = folder / f"{stem} ({n}).md"
    target.write_bytes(shown)
    return f"kept the earlier version of {page} as {target.relative_to(root).as_posix()}"


def stamp(root: Path, only: list[str] | None = None, notes: list[str] | None = None,
          today: datetime.date | None = None) -> list[Finding]:
    """Record the fingerprints of the given pages' originals (all pages when none), keep the version
    each rewritten page replaces, regenerate the start page, and return what is still wrong. With no
    pages given the record is rebuilt whole, which is what clears an orphan; with some, the other
    entries are kept as they are. ``notes`` collects the lines to say."""
    today = today or datetime.date.today()
    notes = notes if notes is not None else []
    pages = [parse_page(root, p) for p in page_paths(root)]
    wanted = None
    if only:
        wanted = set()
        for name in only:
            key = name if name.startswith(LIBRARY + "/") else f"{LIBRARY}/{name}"
            if key not in {p.path for p in pages}:
                raise LibraryError(f"{name} is not a page of the library")
            wanted.add(key)
    try:
        before = load_record(root)
    except LibraryError:
        if wanted is not None:
            raise
        before = {}                     # a whole stamp rebuilds a record it cannot read
    record = {} if wanted is None else dict(before)
    for page in pages:
        if wanted is None or page.path in wanted:
            now = fingerprint(root / page.path)
            was = before.get(page.path, {}).get("page")
            if was and was != now:
                notes.append(_keep_earlier(root, page.path, was, today))
            record[page.path] = {"page": now,
                                 "originals": {o: fingerprint(root / o) for o in page.originals if (root / o).is_file()}}
    record = {p: h for p, h in record.items() if p in {pg.path for pg in pages}}
    (root / RECORD).write_bytes(render_record(record))
    (root / START_PAGE).write_bytes(render_start(pages, history_entries(root)).encode("utf-8"))
    return findings(root)


# -------------------------------------------------------------------- place ----


_STAGE_NOTE = re.compile(r"shell-S(\d+)([a-z]?)(?:-(review|rebuild)-(\d+))?")
_STAGE_NAME = re.compile(r"S\d+[a-z]? - \d+ (?P<label>.+)\.md")
_FINAL_NAME = re.compile(r"\d+ .+\.md")
_DATED_NAME = re.compile(r"\d{4}-\d{2}-\d{2} .+\.md")
_DATE = re.compile(r"\d{4}-\d{2}-\d{2}")


def _title(stem: str) -> str:
    return re.sub(r"[-_]+", " ", stem).strip().title()


def _next_number(folder: Path, pattern: str) -> int:
    numbers = [int(m[1]) for p in folder.glob("*.md") if (m := re.match(pattern, p.name))]
    return max(numbers, default=0) + 1


def _stage_folder(root: Path, number: str) -> Path:
    folders = sorted(p for p in (root / LIBRARY / WORK_HISTORY).glob(f"Stage {number} - *") if p.is_dir())
    if not folders:
        raise LibraryError(f"no folder for stage {number} under {LIBRARY}/{WORK_HISTORY}: a person must "
                           f"name one (Stage {number} - <plain name>) before it gets a page")
    return folders[0]


def _note_date(root: Path, note: str, today: datetime.date | None) -> str:
    source = Path(note) if Path(note).is_absolute() else root / note
    if source.is_file():
        for line in source.read_text(encoding="utf-8").splitlines():
            if found := _DATE.search(line):
                return found[0]
    return (today or datetime.date.today()).isoformat()


def place(root: Path, note: str, today: datetime.date | None = None) -> str:
    """Where a new handoff note's page belongs, repository-relative; deterministic, from the file name.

    Reproduces the library's layout: stage folders in order, the final checks numbered, the rulings
    unnumbered, anything else under Other Work with the note's own date."""
    name = Path(note).name
    stem = name[:-3] if name.endswith(".md") else name
    base = f"{LIBRARY}/{WORK_HISTORY}"
    if m := _STAGE_NOTE.fullmatch(stem):
        number, letter, family, k = m.groups()
        folder = _stage_folder(root, number)
        prefix = f"S{number}{letter}"
        label = "Build" if family is None else f"Review {k}" if family == "review" else f"Fix Round {k}"
        n = _next_number(folder, rf"{re.escape(prefix)} - (\d+) ")
        return f"{base}/{folder.name}/{prefix} - {n:02d} {label}.md"
    bare = stem.removeprefix("shell-")
    if stem.startswith(("shell-final-", "shell-fixpass")):
        n = _next_number(root / LIBRARY / WORK_HISTORY / "Final Checks", r"(\d+) ")
        return f"{base}/Final Checks/{n} {_title(bare)}.md"
    if stem.startswith(("shell-rulings", "shell-ledger", "shell-spec-sync")):
        return f"{base}/Jason's Rulings and Plan Updates/{_title(bare)}.md"
    return f"{base}/Other Work/{_note_date(root, note, today)} {_title(stem)}.md"


# ----------------------------------------------------------------- organize ----


def _stage_order(note: str) -> tuple:
    """Build first, then review k and fix round k in turn - the order a stage happened in."""
    m = _STAGE_NOTE.fullmatch(Path(note).stem)
    family, k = m[3], int(m[4] or 0)
    return (0, 0, 0) if family is None else (1, k, 0 if family == "review" else 1)


def _in_head(root: Path, path: str) -> bool | None:
    """Is ``path`` in Git's ``HEAD``? ``None`` when Git cannot say (not installed, not a repository,
    no commit yet), and then nothing is retired: only a committed deletion proves a file is gone."""
    try:
        head = subprocess.run(["git", "rev-parse", "--verify", "-q", "HEAD"], cwd=root,
                              capture_output=True, timeout=30)
        if head.returncode != 0:
            return None
        return subprocess.run(["git", "cat-file", "-e", f"HEAD:{path}"], cwd=root,
                              capture_output=True, timeout=30).returncode == 0
    except (OSError, subprocess.SubprocessError):
        return None


def _removed_in_git(root: Path, path: str) -> bool:
    """Was ``path`` committed once and removed since? Only that proves a page's file is gone: a file
    that is merely missing from the working tree, or was never committed (a new note renamed before
    its first commit), is the agent's to fix on the page, never a retirement (review 2)."""
    if _in_head(root, path) is not False:
        return False
    try:
        seen = subprocess.run(["git", "log", "-1", "--format=%H", "--", path], cwd=root,
                              capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return False
    return seen.returncode == 0 and bool(seen.stdout.strip())


def _contains_a_name(name: str, originals: tuple[str, ...]) -> bool:
    low = name.lower()
    for original in originals:
        path = Path(original)
        for known in (path.name, path.stem, path.parent.name):
            if known and known.lower() in low:
                return True
    return False


def _targets(root: Path, pages: list[Page], today: datetime.date) -> tuple[dict[str, str], list[Finding]]:
    """Where each page belongs: ``{current path: target path}`` for the pages that must move, and a
    refusal for each that cannot. Pure of side effects; the rules of section 9.1 in order."""
    moves: dict[str, str] = {}
    refused: list[Finding] = []
    lib = LIBRARY + "/"
    notes = set(note_paths(root))
    stage_groups: dict[tuple[str, str], list[tuple[tuple, str, Page]]] = {}
    numbered: dict[str, int] = {}
    for page in pages:
        name = Path(page.path).name
        if page.originals and not any((root / o).is_file() for o in page.originals) \
                and all(_removed_in_git(root, o) for o in page.originals):
            moves[page.path] = f"{lib}{ARCHIVE}/{RETIRED}/{page.path[len(lib):]}"
            continue
        note = next((o for o in page.originals if o in notes), None)
        if page.kind == "Overview":
            moves[page.path] = f"{lib}{START}/{name}"
        elif page.kind == PROGRAM_KIND and page.topics and page.topics[0] in PROGRAM_HOMES:
            section, default = PROGRAM_HOMES[page.topics[0]]
            inside = page.path.startswith(f"{lib}{section}/")
            folder = Path(page.path).parent.as_posix() if inside else f"{lib}{section}/{default}".rstrip("/")
            if not _contains_a_name(name, page.originals):
                name = f"{Path(page.path).stem} ({Path(page.originals[0]).name}).md"
            moves[page.path] = f"{folder}/{name}"
        elif page.kind in KINDS and page.kind != PROGRAM_KIND and note is not None:
            stem = Path(note).stem
            if m := _STAGE_NOTE.fullmatch(stem):
                try:
                    folder = _stage_folder(root, m[1])
                except LibraryError as exc:
                    refused.append(Finding("organize", page.path, (note,), f"{page.path}: {exc}.",
                                           "a person names the stage folder; then run organize"))
                    continue
                shape = _STAGE_NAME.fullmatch(name)
                label = shape["label"] if shape else \
                    ("Build" if m[3] is None else f"Review {m[4]}" if m[3] == "review" else f"Fix Round {m[4]}")
                stage_groups.setdefault((folder.relative_to(root).as_posix(), f"S{m[1]}{m[2]}"), []) \
                    .append((_stage_order(note), label, page))
            elif stem.startswith(("shell-final-", "shell-fixpass")):
                folder = f"{lib}{WORK_HISTORY}/Final Checks"
                if not _FINAL_NAME.fullmatch(name):
                    numbered[folder] = numbered.get(folder, _next_number(root / folder, r"(\d+) ") - 1) + 1
                    name = f"{numbered[folder]} {_title(stem.removeprefix('shell-'))}.md"
                moves[page.path] = f"{folder}/{name}"
            elif stem.startswith(("shell-rulings", "shell-ledger", "shell-spec-sync")):
                moves[page.path] = f"{lib}{WORK_HISTORY}/Jason's Rulings and Plan Updates/{name}"
            else:
                if not _DATED_NAME.fullmatch(name):
                    name = f"{_note_date(root, note, today)} {_title(stem)}.md"
                moves[page.path] = f"{lib}{WORK_HISTORY}/Other Work/{name}"
    for (folder, prefix), members in stage_groups.items():
        for n, (_, label, page) in enumerate(sorted(members, key=lambda m: (m[0], m[2].path)), 1):
            moves[page.path] = f"{folder}/{prefix} - {n:02d} {label}.md"
    return {src: dst for src, dst in moves.items() if src != dst}, refused


def organize(root: Path, dry_run: bool = False, today: datetime.date | None = None) -> tuple[list[str], list[Finding]]:
    """Move and rename pages to where the rules say; returns the lines to say and the refusals.

    Never edits a page but for the Retired line, never overwrites a file, and carries a moved page's
    record in ``pages.json`` to its new path (its originals did not change, so it is no staler than
    before). A page whose file was removed is retired. With ``dry_run`` nothing changes."""
    today = today or datetime.date.today()
    pages = [parse_page(root, p) for p in page_paths(root)]
    moves, refused = _targets(root, pages, today)
    staying = {p.path for p in pages} - set(moves)
    claimed: dict[str, list[str]] = {}
    for src, dst in moves.items():
        claimed.setdefault(dst, []).append(src)
    ok: dict[str, str] = {}
    for src, dst in sorted(moves.items()):
        if len(claimed[dst]) > 1 or dst in staying or ((root / dst).exists() and dst not in moves):
            refused.append(Finding("organize", src, (), f"{src} belongs at {dst}, which is taken by a different file.",
                                   "rename or merge one of the two pages by hand; organize never overwrites"))
        else:
            ok[src] = dst
    lines = [f"{'would move' if dry_run else 'moved'}: {src} -> {dst}" for src, dst in sorted(ok.items())]
    if dry_run or not ok:
        return lines, sorted(refused)
    record = load_record(root) if (root / RECORD).is_file() else {}
    undo: list[tuple[Path, Path]] = []                         # (where it is now, where it came from)
    restore: dict[Path, bytes] = {}                            # a retired page's text before its Retired line
    try:
        for n, src in enumerate(sorted(ok)):                   # two phases, so a chain of renames cannot collide
            (root / src).rename(root / f"{src}.organize-{n}")
            undo.append((root / f"{src}.organize-{n}", root / src))
        for n, (src, dst) in enumerate(sorted(ok.items())):
            target = root / dst
            target.parent.mkdir(parents=True, exist_ok=True)
            (root / f"{src}.organize-{n}").rename(target)
            undo[n] = (target, root / src)
        for src, dst in sorted(ok.items()):
            if dst.startswith(f"{LIBRARY}/{ARCHIVE}/{RETIRED}/"):
                restore[root / dst] = (root / dst).read_bytes()
                _write_retired_line(root / dst, today)
                record.pop(src, None)
    except Exception as exc:
        stuck = _roll_back(undo, restore)                      # a half-done organize is worse than none
        said = ("every rename already made was put back where it was" if not stuck else
                "these could not be put back and are named here so nothing is lost: " + "; ".join(stuck))
        raise LibraryError(f"organize failed ({type(exc).__name__}: {exc}); {said}") from exc
    for src, dst in ok.items():
        if src in record:
            record[dst] = record.pop(src)
    if record or (root / RECORD).is_file():
        (root / RECORD).write_bytes(render_record(record))
    for src in ok:                                            # empty folders a move left behind
        folder = (root / src).parent
        while folder != root / LIBRARY and folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()
            folder = folder.parent
    pages = [parse_page(root, p) for p in page_paths(root)]
    (root / START_PAGE).write_bytes(render_start(pages, history_entries(root)).encode("utf-8"))
    return lines, sorted(refused)


def _roll_back(undo: list[tuple[Path, Path]], restore: dict[Path, bytes]) -> list[str]:
    """Put every page back, in two phases like the move itself, so two pages that swapped names can
    never land on each other, and never over an existing file (``rename`` would overwrite one on
    POSIX). Returns a sentence for each page it could not put back, naming where it now is."""
    stuck: list[str] = []
    parked: list[tuple[Path, Path]] = []
    for n, (now, was) in enumerate(undo):
        try:
            if now in restore:
                now.write_bytes(restore[now])
            aside = now.with_name(f"{now.name}.organize-undo-{n}")
            if aside.exists():
                raise FileExistsError(aside)
            now.rename(aside)
            parked.append((aside, was))
        except OSError as exc:
            stuck.append(f"{now} (meant for {was}: {type(exc).__name__})")
    for aside, was in parked:
        try:
            if was.exists():
                raise FileExistsError(was)
            aside.rename(was)
        except OSError as exc:
            stuck.append(f"{aside} (meant for {was}: {type(exc).__name__})")
    return stuck


def _write_retired_line(path: Path, today: datetime.date) -> None:
    """The one text edit organize makes: say, after the Tags line, that the original is gone."""
    lines = path.read_text(encoding="utf-8").split("\n")
    at = next((i for i, ln in enumerate(lines) if ln.startswith("**Tags:**")),
              next((i for i, ln in enumerate(lines) if ln.startswith("**Original file:**")), 0))
    lines.insert(at + 1, f"**Retired:** {today.isoformat()} - the file it explained was removed.  ")
    path.write_bytes("\n".join(lines).encode("utf-8"))


# --------------------------------------------------------------------- hook ----


def hook(root: Path, stdin_text: str) -> tuple[int, str, str]:
    """The Stop hook: ``(exit code, stdout, stderr)``.

    It runs ``organize`` first - the mechanical part fixes itself - then ``check``. Pages it moved are
    listed, with the order to stage them and refresh the code map. Exit 2 with the work order on stderr keeps a Claude Code session going with that text
    as its instruction; an organize refusal is a finding in it. A session that already tried once
    (``stop_hook_active``) gets a warning on stdout and exit 0, so one that cannot fix the library is
    never trapped; the test and CI still hold the line. A broken hook must never block work, so any
    error is a one-line warning and exit 0."""
    try:
        try:
            active = bool(json.loads(stdin_text or "{}").get("stop_hook_active"))
        except (json.JSONDecodeError, AttributeError):
            active = False
        moved, refused = organize(root, dry_run=active)
        said = "".join(f"{line}\n" for line in moved)
        found = sorted(refused + findings(root))
        text = ""
        if moved:
            text += (said + "The plain-English library organizer moved these pages: stage these moves "
                     "(git add -A \"docs/For NonCoders\") and run python tools/repo_map.py update\n")
        if found:
            text += ("The plain-English library (docs/For NonCoders) is out of date:\n"
                     + work_order(found, HOOK_LIMIT) + "\n")
        if not text:
            return 0, "", ""
        return (0, text, "") if active else (2, "", text)
    except Exception as exc:  # noqa: BLE001 - a broken hook must never block work
        return 0, f"noncoder_pages hook skipped: {type(exc).__name__}\n", ""


# --------------------------------------------------------------------- CLI ----


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):        # a Windows console's code page must not crash a report
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check", help="verify the library is current; exit 1 if not")
    sub.add_parser("todo", help="print what is out of date as a work order")
    stamp_cmd = sub.add_parser("stamp", help="record fingerprints and regenerate the start page")
    stamp_cmd.add_argument("pages", nargs="*", help="pages to stamp (default: all)")
    place_cmd = sub.add_parser("place", help="print where a new handoff note's page belongs")
    place_cmd.add_argument("note")
    organize_cmd = sub.add_parser("organize", help="move and rename pages to where the rules say")
    organize_cmd.add_argument("--dry-run", action="store_true", help="print the moves without making them")
    sub.add_parser("hook", help="the Claude Code Stop hook")
    ns = parser.parse_args(argv)
    try:
        if ns.command == "hook":
            try:
                stdin_text = sys.stdin.read()
            except (OSError, UnicodeDecodeError):
                stdin_text = ""
            code, out, err = hook(ROOT, stdin_text)
            sys.stdout.write(out)
            sys.stderr.write(err)
            return code
        if ns.command == "place":
            print(place(ROOT, ns.note))
            return 0
        if ns.command == "organize":
            moved, refused = organize(ROOT, ns.dry_run)
            if moved:
                print("\n".join(moved))
            for f in refused:
                print(f"refused: {f.problem} {f.fix}", file=sys.stderr)
            return 1 if refused else 0
        if ns.command == "stamp":
            notes: list[str] = []
            left = stamp(ROOT, ns.pages, notes)
            print("\n".join(notes + [f"Stamped {RECORD} and {START_PAGE}."]))
            if left:
                print(f"Still out of date ({len(left)}):\n" + work_order(left))
            return 1 if left else 0
        found = findings(ROOT)
        if ns.command == "todo":
            moved, refused = organize(ROOT, dry_run=True)
            found = sorted(refused + found)
            if moved:
                print("organize would first do (run: python tools/noncoder_pages.py organize):\n" + "\n".join(moved))
            print(work_order(found) if found else "The plain-English library is current; nothing to do.")
            return 0
        if not found:
            print("The plain-English library is current.")
            return 0
        for f in found:
            print(f"[{f.kind}] {f.problem} Fix: {f.fix}")
        return 1
    except LibraryError as exc:
        print(f"noncoder_pages: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
