"""Which keyword is reached by which document: the vocabulary coverage report.

Every request row in ``tracker/templates.py`` recognises its document by
keywords, and twelve adversarial readings (decisions 54-69) tuned those
keywords one confusable at a time. What no reading could see is the
whole: which keywords the IRS forms in ``tests/irs/`` and the
reconstructed cases in ``tests/test_catalog.py`` actually reach, and
which are defended by nothing. A keyword no document in the suite says
is one that can misfile tomorrow with no test to say so. This report is
that whole, generated the way the suite routes: each catalog built
through ``create_template()`` and ``load_manifest()``, each corpus form
read by ``content_check.extract_text()``, each keyword tested with
``says()``, the reading the router and the scanner share.

Four lists matter, per catalog:

- **unreached** - keywords no corpus form and no case says. Nothing
  defends them; a review round starts there.
- **reached only elsewhere** - keywords said only by documents the suite
  files under another row or parks. The row's other rules are all that
  keep those documents out: a misfiling one rule slip away.
- **reached without an expectation** - keywords said only by documents
  the suite never routes against this catalog (a case written for
  another catalog, a corpus form with no placement here). Reached, but
  proven nothing; the cheapest placements to add.
- **rows without a filing document** - rows the suite never files a
  document into, so their keywords are proven only in the negative.

Like the repository map, the report is derived and committed, and
``check`` says whether the committed one still matches its inputs: the
catalog, the matcher, the loader, the corpus, the case list and the
harnesses that carry their placements, each by its SHA-256, so the check
costs nothing and a change to any of them turns it red until ``build``
runs again.

The committed report never reads a client document: the corpus is the
IRS's own blank forms (public domain) and the text the suite typed. When
``ENV_REAL_CORPUS`` names the firm's own redacted documents, ``build``
reads those too, so a review round sees which keywords the documents a
client actually sends reach - but that report names files nobody
redacted the names of, so it is a local reading and not the committed
one: ``check`` refuses a committed report built with them, and the
corpus itself is never in the repository to be hashed.

A case's text is read as typed; the suite prints it to a PDF and reads
it back, which preserves its lines, so the two readings agree on every
keyword the report has been checked against. A workbook case is rendered
the way ``content_check._extract_xlsx`` renders a sheet (``as_a_sheet``),
for the same reason: half of every catalog asks for a schedule a client
keeps in Excel, and a sheet is read as rows of tab-separated cells, not
as prose.

::

    python tools/vocab_report.py build      # rebuild docs/vocab-coverage.json and .md
    python tools/vocab_report.py check      # is the committed report current? exit 1 if not
    python tools/vocab_report.py show 1040  # one catalog, row by row
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))   # run as a script: the package and the suite must import

from tracker.content_check import dominant_forms, extract_text, says  # noqa: E402
from tracker.manifest import RequestItem, create_template, load_manifest  # noqa: E402
from tracker.settings import ENV_REAL_CORPUS, EXPECTATIONS_FILENAME  # noqa: E402
from tracker.templates import FORM_TEMPLATES, template_items  # noqa: E402

REPORT_PATH = ROOT / "docs" / "vocab-coverage.json"
MARKDOWN_PATH = ROOT / "docs" / "vocab-coverage.md"
IRS_DIR = ROOT / "tests" / "irs"
SCHEMA_VERSION = 1
GENERATED_NOTE = "GENERATED by tools/vocab_report.py — do not edit by hand."
#: Everything the report is a function of. A change to any of these makes
#: the committed report stale; nothing else does.
INPUT_PATHS = (
    "tracker/templates.py",       # the catalog
    "tracker/content_check.py",   # says(), the matcher
    "tracker/manifest.py",        # the loader's defaults
    "tests/test_catalog.py",      # the cases
    "tests/test_irs_forms.py",    # the corpus's expected placements
    "tests/test_real_corpus.py",  # how the firm's own documents are read
    "tools/vocab_report.py",      # this generator
)

IRS, CASE, REAL = "irs", "case", "real"
REQUIRED, ANY = "required", "any"


class ReportError(Exception):
    """The report could not be built, read or checked."""


@dataclass(frozen=True, slots=True)
class Document:
    """One document the report routes: a corpus form, a typed case, or a real one."""

    kind: str                 # IRS, CASE or REAL
    name: str
    text: str
    #: catalog -> where the suite says it belongs there (an identifier, or
    #: None for "parks"). A catalog absent here has no expectation.
    expected: dict[str, str | None] = field(default_factory=dict)
    decision: int = 0         # the case's decision; 0 for a corpus form


# ------------------------------------------------------------------ inputs ----


def input_hashes(root: Path | None = None) -> dict[str, str]:
    """SHA-256 of every input, by repo-relative path, the corpus forms included."""
    root = root or ROOT
    paths = [root / p for p in INPUT_PATHS] + sorted((root / "tests" / "irs").glob("*.pdf"))
    return {
        p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in paths
    }


def shipped_catalogs() -> dict[str, list[RequestItem]]:
    """Every catalog as an engagement gets it: written to a manifest and loaded back."""
    catalogs: dict[str, list[RequestItem]] = {}
    with tempfile.TemporaryDirectory() as folder:
        for form in FORM_TEMPLATES:
            manifest = Path(folder) / f"{form}.xlsx"
            create_template(manifest, template_items(form))
            catalogs[form] = load_manifest(manifest)
    return catalogs


def _placements(rows: list[tuple[str, str, int, str | None]]) -> dict[str, dict[str, str | None]]:
    """``(name, catalog, year, where)`` rows as document -> catalog -> placement.

    One document is routed against several catalogs and must be expected
    in the same place each time it is; a row that contradicts an earlier
    one is the expectation file disagreeing with itself, and is raised
    rather than resolved.
    """
    expected: dict[str, dict[str, str | None]] = {}
    for name, form, _year, where in rows:
        known = expected.setdefault(name, {})
        if form in known and known[form] != where:
            raise ReportError(f"{name} is expected at both {known[form]} and {where} in the {form} catalog")
        known[form] = where
    return expected


def corpus_documents() -> list[Document]:
    """The IRS forms, read as the router reads them, with the suite's placements."""
    from tests.test_irs_forms import EXPECT

    expected = _placements(EXPECT)
    documents = []
    for path in sorted(IRS_DIR.glob("*.pdf")):
        text = extract_text(path) or ""
        documents.append(Document(IRS, path.name, text, expected.get(path.name, {})))
    return documents


def real_documents() -> list[Document]:
    """The firm's own redacted documents, when ``ENV_REAL_CORPUS`` names them.

    The harness owns the reading, so the report and the test cannot
    disagree about what an expectation means. Nothing here is committed:
    with no corpus this is an empty list, which is what CI and the
    committed report are built from.
    """
    from tests.test_real_corpus import real_corpus

    folder, rows = real_corpus()
    if folder is None:
        return []
    documents = []
    for name, expected in sorted(_placements(rows).items()):
        path = folder / name
        if not path.is_file():
            raise ReportError(f"{EXPECTATIONS_FILENAME} names {name}, which is not in {folder}")
        documents.append(Document(REAL, name, extract_text(path) or "", expected))
    return documents


#: The sheet name openpyxl gives a new workbook, which ``_extract_xlsx``
#: reads as the sheet's first line.
_SHEET_NAME = "Sheet"


def as_a_sheet(rows: list[list]) -> str:
    """A workbook case as ``content_check._extract_xlsx`` renders it: the
    sheet's name, then one line per row with its cells set apart by a tab.

    The suite writes these cases to a real .xlsx and reads them back; the
    report renders them instead, so that both see the same text and a
    keyword that spans two cells is reached in both.
    """
    lines = [_SHEET_NAME]
    for row in rows:
        cells = [str(value) for value in row if value is not None]
        if cells:
            lines.append("\t".join(cells))
    return "\n".join(lines)


def case_documents() -> list[Document]:
    """The reconstructed cases, each expected somewhere in the catalog it was written for.

    Both kinds: the pages typed as lines, and the workbooks typed as rows
    (half of every catalog asks for a schedule a client keeps in Excel).
    """
    from tests.test_catalog import CASES, XLSX_CASES

    documents = [
        Document(CASE, name, "\n".join(lines), {form: where}, decision)
        for decision, form, name, lines, where in CASES
    ]
    documents += [
        Document(CASE, name, as_a_sheet(rows), {form: where}, decision)
        for decision, form, name, rows, where in XLSX_CASES
    ]
    return documents


# ------------------------------------------------------------------ report ----


def report(catalogs: dict[str, list[RequestItem]], documents: list[Document]) -> dict:
    """The coverage of ``catalogs`` by ``documents``; pure, and what the tests exercise."""
    prepared = [(doc, doc.text.lower(), dominant_forms(doc.text)) for doc in documents]
    out: dict = {"schema": SCHEMA_VERSION, "note": GENERATED_NOTE, "catalogs": {}}
    totals = {"rows": 0, "keywords": 0, "unreached": 0, "reached_only_elsewhere": 0,
              "reached_without_expectation": 0, "rows_without_a_filing_document": 0}
    for form in sorted(catalogs):
        rows_out: dict[str, dict] = {}
        unreached: list[list[str]] = []
        only_elsewhere: list[list[str]] = []
        no_expectation: list[list[str]] = []
        no_filing: list[str] = []
        for row in catalogs[form]:
            keywords = [(k, REQUIRED) for k in row.required_keywords] + [(k, ANY) for k in row.any_keywords]
            listed = []
            filed_here = False
            # Keywords outermost: a keyword's patterns are compiled once and
            # reused across every document, instead of recompiled per document.
            for keyword, rule in keywords:
                hits = []
                for doc, low, dominant in prepared:
                    if not says(low, keyword, dominant):
                        continue
                    hit: dict = {"kind": doc.kind, "name": doc.name}
                    if doc.decision:
                        hit["decision"] = doc.decision
                    if form in doc.expected:
                        hit["expected"] = doc.expected[form]
                    hits.append(hit)
                hits.sort(key=lambda h: (h["kind"], h.get("decision", 0), h["name"]))
                listed.append({"keyword": keyword, "rule": rule, "reached_by": hits})
                here = any(h.get("expected") == row.identifier for h in hits)
                filed_here = filed_here or here
                if not hits:
                    unreached.append([row.identifier, keyword])
                elif not here and any("expected" in h for h in hits):
                    only_elsewhere.append([row.identifier, keyword])
                elif not here:
                    no_expectation.append([row.identifier, keyword])
            rows_out[row.identifier] = {"document": row.document, "keywords": listed}
            if not filed_here:
                no_filing.append(row.identifier)
        out["catalogs"][form] = {
            "rows": rows_out,
            "unreached": unreached,
            "reached_only_elsewhere": only_elsewhere,
            "reached_without_expectation": no_expectation,
            "rows_without_a_filing_document": no_filing,
        }
        totals["rows"] += len(rows_out)
        totals["keywords"] += sum(len(r["keywords"]) for r in rows_out.values())
        totals["unreached"] += len(unreached)
        totals["reached_only_elsewhere"] += len(only_elsewhere)
        totals["reached_without_expectation"] += len(no_expectation)
        totals["rows_without_a_filing_document"] += len(no_filing)
    counted = {kind: sum(d.kind == kind for d in documents) for kind in (IRS, CASE, REAL)}
    out["counts"] = totals | {
        "catalogs": len(catalogs),
        # The real corpus is absent from a report built without one, so the
        # committed report says nothing about documents it never read.
        "documents": {kind: n for kind, n in counted.items() if n or kind != REAL},
    }
    return out


def build() -> dict:
    """The report over the shipped catalogs, the corpus, the cases and any real documents."""
    result = report(shipped_catalogs(), corpus_documents() + case_documents() + real_documents())
    result["inputs"] = input_hashes()
    return result


def real_documents_in(data: dict) -> int:
    """How many of the firm's own documents a report was built from."""
    return int(data.get("counts", {}).get("documents", {}).get(REAL, 0))


# ---------------------------------------------------------------- markdown ----


def _arrow(hit: dict, identifier: str) -> str:
    if "expected" not in hit:
        return "?"
    if hit["expected"] == identifier:
        return "**here**"
    return "parks" if hit["expected"] is None else hit["expected"]


def _hit_label(hit: dict) -> str:
    return f"{hit['name']} (d{hit['decision']})" if hit.get("decision") else hit["name"]


def render_markdown(data: dict) -> str:
    counts = data["counts"]
    real = real_documents_in(data)
    lines = [
        "# Vocabulary coverage",
        "",
        f"<!-- {data['note']} -->",
        "",
        "Which keyword is reached by which document: every catalog row's keywords against the "
        "IRS forms in `tests/irs/` and the reconstructed cases in `tests/test_catalog.py`, "
        "tested with `says()` the way the router and the scanner read. Rebuild with "
        "`python tools/vocab_report.py build`; `check` says whether this matches its inputs.",
        "",
        f"{counts['catalogs']} catalogs · {counts['rows']} rows · {counts['keywords']} keywords · "
        f"**{counts['unreached']} unreached** · {counts['reached_only_elsewhere']} reached only elsewhere · "
        f"{counts['reached_without_expectation']} reached without an expectation · "
        f"{counts['rows_without_a_filing_document']} rows without a filing document · "
        f"{counts['documents'][IRS]} IRS forms · {counts['documents'][CASE]} cases"
        + (f" · {real} real documents" if real else ""),
        "",
        "A hit reads *document → where the suite files it in this catalog*: **here** is this row, "
        "*parks* is Needs Review, another identifier is another row, and `?` means the suite has "
        "no expectation for that document in this catalog.",
        "",
    ]
    catalogs = data["catalogs"]

    lines += ["## Unreached keywords", "",
              "Said by no corpus form and no case. Nothing defends them.", ""]
    any_unreached = False
    for form, entry in catalogs.items():
        for identifier, keyword in entry["unreached"]:
            lines.append(f"- **{form} {identifier}** `{keyword}`")
            any_unreached = True
    if not any_unreached:
        lines.append("- none")
    lines.append("")

    for heading, key, intro in (
        ("Keywords reached only by documents that file elsewhere or park", "reached_only_elsewhere",
         "The row's other rules are all that keep those documents out."),
        ("Keywords reached only by documents the suite never routes against this catalog",
         "reached_without_expectation",
         "Reached, but proven nothing: the cheapest placements to add."),
    ):
        lines += [f"## {heading}", "", intro, ""]
        listed_any = False
        for form, entry in catalogs.items():
            for identifier, keyword in entry[key]:
                lines.append(f"- **{form} {identifier}** `{keyword}`")
                listed_any = True
        if not listed_any:
            lines.append("- none")
        lines.append("")

    lines += ["## Rows the suite never files a document into", ""]
    any_row = False
    for form, entry in catalogs.items():
        for identifier in entry["rows_without_a_filing_document"]:
            lines.append(f"- **{form} {identifier}** — {entry['rows'][identifier]['document']}")
            any_row = True
    if not any_row:
        lines.append("- none")
    lines.append("")

    for form, entry in catalogs.items():
        lines += [f"## {form}", ""]
        for identifier, row in entry["rows"].items():
            lines += [f"### {identifier} — {row['document']}", ""]
            for kw in row["keywords"]:
                if kw["reached_by"]:
                    hits = "; ".join(f"{_hit_label(h)} → {_arrow(h, identifier)}" for h in kw["reached_by"])
                else:
                    hits = "*unreached*"
                lines.append(f"- `{kw['keyword']}` ({kw['rule']}) — {hits}")
            lines.append("")
    return "\n".join(lines)


def write_outputs(data: dict, report_path: Path | None = None, markdown_path: Path | None = None) -> None:
    report_path = report_path or REPORT_PATH
    markdown_path = markdown_path or MARKDOWN_PATH
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_bytes((json.dumps(data, indent=1, sort_keys=True) + "\n").encode("utf-8"))
    markdown_path.write_bytes(render_markdown(data).encode("utf-8"))


def load_report(report_path: Path | None = None) -> dict:
    report_path = report_path or REPORT_PATH
    try:
        data = json.loads(report_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ReportError(f"no report at {report_path}; run: python tools/vocab_report.py build") from None
    except (json.JSONDecodeError, OSError) as exc:
        raise ReportError(f"could not read {report_path}: {exc}") from None
    if data.get("schema") != SCHEMA_VERSION:
        raise ReportError(f"{report_path} is schema {data.get('schema')!r}, this tool writes {SCHEMA_VERSION}; rebuild it")
    return data


def stale_inputs(data: dict, root: Path | None = None) -> list[str]:
    """The inputs whose hash differs from what the report was built from, by path."""
    recorded = data.get("inputs", {})
    current = input_hashes(root)
    return sorted(p for p in set(recorded) | set(current) if recorded.get(p) != current.get(p))


# --------------------------------------------------------------------- CLI ----


def _cmd_build(_ns: argparse.Namespace) -> int:
    data = build()
    write_outputs(data)
    c = data["counts"]
    print(f"Built {REPORT_PATH.relative_to(ROOT)}: {c['keywords']} keywords in {c['rows']} rows, "
          f"{c['unreached']} unreached, {c['reached_only_elsewhere']} reached only elsewhere")
    if real := real_documents_in(data):
        print(f"It names {real} document(s) from {ENV_REAL_CORPUS}: read it, do not commit it.")
    return 0


def _cmd_check(_ns: argparse.Namespace) -> int:
    data = load_report()
    if real := real_documents_in(data):
        # A report built on a machine with a corpus names the firm's own
        # files; committing it would put client names in the repository.
        print(f"Report is STALE — it names {real} document(s) from {ENV_REAL_CORPUS}, which are never committed."
              f"\n\nRebuild it with the variable unset: python tools/vocab_report.py build")
        return 1
    stale = stale_inputs(data)
    if not stale and MARKDOWN_PATH.exists() and MARKDOWN_PATH.read_text(encoding="utf-8") == render_markdown(data):
        c = data["counts"]
        print(f"Report is current ({c['keywords']} keywords, {c['unreached']} unreached).")
        return 0
    if stale:
        print(f"Report is STALE — {len(stale)} input(s) changed since it was built:")
        for path in stale:
            print(f"  {path}")
    else:
        print(f"Report is STALE — {MARKDOWN_PATH.relative_to(ROOT)} does not match the JSON.")
    print("\nRebuild it with: python tools/vocab_report.py build")
    return 1


def _cmd_show(ns: argparse.Namespace) -> int:
    data = load_report()
    entry = data["catalogs"].get(ns.catalog)
    if entry is None:
        print(f"No catalog {ns.catalog!r}; the report has: {', '.join(data['catalogs'])}")
        return 1
    for identifier, row in entry["rows"].items():
        print(f"[{identifier}] {row['document']}")
        for kw in row["keywords"]:
            hits = ", ".join(f"{_hit_label(h)} -> {_arrow(h, identifier).strip('*')}" for h in kw["reached_by"])
            print(f"    {kw['keyword']!r} ({kw['rule']}): {hits or 'UNREACHED'}")
    for label in ("unreached", "reached_only_elsewhere", "reached_without_expectation",
                  "rows_without_a_filing_document"):
        print(f"\n{label.replace('_', ' ')}: {entry[label] or 'none'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("build", help="rebuild the report from the catalog, the corpus and the cases")
    sub.add_parser("check", help="verify the committed report matches its inputs; exit 1 if stale")
    show = sub.add_parser("show", help="print one catalog's rows and what reaches each keyword")
    show.add_argument("catalog", help="a catalog id, e.g. 1040")

    ns = parser.parse_args(argv)
    commands = {"build": _cmd_build, "check": _cmd_check, "show": _cmd_show}
    try:
        return commands[ns.command](ns)
    except ReportError as exc:
        print(f"vocab_report: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
